---
title: "Dryad Soil Data Wrangling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, include = FALSE}
# install.packages("tindyverse")
# install.packages("readxl")
library("readxl")
library("tidyverse")
library("dplyr")
library("openintro")
library("skimr")
library("janitor")
```


## R Markdown
## Explore Sandborn Lewis Data, clean col names, convert to lowercase
```{r read-in-sandborn_lewis_data, eval= FALSE, warning = F}
data <- read_excel("1 Sandborn Lewis data.xlsx") %>%  
  janitor::clean_names() %>% 
  rename_with(tolower) %>%
  mutate(bulk_density = as.numeric(bulk_density),
         depth1 = as.numeric(depth1),
         depth2 = as.numeric(depth2),
         cconc = as.numeric(cconc),
         total_depth=depth2-depth1)
glimpse(data)
```

## Retain Tidy Excel Columns A-F,J-L, Q, S; create new dataframe sandborn_lewis_select_variables

```{r new-dataframe-with-select-variables, eval = FALSE}
data_subset <- data %>% 
  select(source, id, order, lat, lon, latlon_q, horizon, depth1, depth2, total_depth, bulk_density, cconc)
glimpse(data_subset)
``` 

## Create an index column specifiying if a value is gap-filled or not

Create a vector of gap-filled values

```{r gap-filled-values}
bd_fill_values <- data_subset %>%
  select(bulk_density) %>%
  slice(1:3, 8:10, 16:28, 34:39, 46:146) %>%
  filter(!is.na(bulk_density)) %>% 
  distinct() %>% 
  pull() 
bd_fill_values
```

Create the `gap_filled` index column

```{r create-gap-filled-index}
data_subset <- data_subset %>% 
  mutate(bd_filled = ifelse(bulk_density %in% bd_fill_values, "yes", "no")) 
data_subset
```


